### ISSUE TITLE
CSS not live reloaded

### ISSUE THREAD

**Issue by jgautheron** [StartPolymer/polymer-starter-kit-plus#16]
When editing the CSS of a component, `gulp serve` won't reload the new styles.

**Comment by JosefJezek** [comment]
I will look at it...

**Comment by JosefJezek** [comment]
Reload new styles is working for editing CSS style in `my-list.html`. Please send me your changes.

**Comment by jgautheron** [comment]
I make changes in [page.css](https://github.com/StartPolymer/polymer-starter-kit-plus/blob/master/app/themes/default-theme/components/page.css)
The changes are detected and the page `index.html` reloaded, but without the changes applied.
If I look in the `.tmp` folder, the generated `theme.html` is not updated.
