### ISSUE TITLE
JS doesn't reload BrowserSync anytime after JSLint error

### ISSUE THREAD

**Issue by lukeed** [StartPolymer/polymer-starter-kit-plus#25]
Added reload to the gulp watcher:

```javascript
gulp.watch(['app/{scripts,elements}/**/*.{js,html}'], ['jshint', 'js', reload]);
```

Now anytime a JSLint finds an error, BrowserSync will never reload on JS changes --- even after the error(s) have been fixed.

**Comment by JosefJezek** [comment]
I will be to fix it...

**Comment by JosefJezek** [comment]
Fixed
