### ISSUE TITLE
Icons defined in iron-icons/iron-icons.html cannot be used due to iconset name collision

### ISSUE THREAD

**Issue by Artanis** [StartPolymer/polymer-starter-kit-plus#34]
Both [iron-icons/iron-icons.html](https://github.com/PolymerElements/iron-icons/blob/master/iron-icons.html#L40) and [app/themes/default-theme/icons.html](https://github.com/StartPolymer/polymer-starter-kit-plus/blob/master/app/themes/default-theme/icons.html#L4) define an icon set `icons`.

`default-theme` usually loads last and ends up clobbering `iron-icons`.

The iconset defined in `default-theme` should be renamed, and current unprefixed icon references should be prefixed with that name.

**Comment by JosefJezek** [comment]
Yes, default theme using custom icons. `iron-icons` element is large file. You can copy svg icons from `iron-icons` to [icons.html](https://github.com/StartPolymer/polymer-starter-kit-plus/blob/master/app/themes/default-theme/icons.html#L4)

Check out this video...
https://www.youtube.com/watch?v=tjmRUgUca1g

**Comment by JosefJezek** [comment]
https://github.com/StartPolymer/polymer-starter-kit-plus/commit/50bb48e90e58fd0dcb447ab6517c0b5e4c9107ec

**Comment by Artanis** [comment]
Huh. Dunno how I missed that Polycasts episode. That does make a great deal of sense... however, I still feel that it's not ideal to clobber the `icons` set.

I also don't think _manually_ maintaining copies of all the icons you use is a good idea, but the limits of this optimization are better discussed at `iron-icons` (PolymerElements/iron-icons#19, for example).

**Comment by JosefJezek** [comment]
We need custom pack of icons for high performance. ;-)
