### ISSUE TITLE
context stacking and z-index

### ISSUE THREAD

**Issue by bkr32** [StartPolymer/polymer-starter-kit-plus#46]
over the last week i've faced a few issues with stacking elements such as paper-dialog modal and items that use z-index, while using paper-dialog modal the whole screen loses focus including the dialog and while using z-index even at 1 it overlaps all other items such as toolbar and scrollable header, 

i have not experienced these issues before and i am not sure if i am the only one experiencing these, 
i will be happy to provide code and log if required, thank you

**Comment by JosefJezek** [comment]
Please provideme your code...

**Comment by bkr32** [comment]
`<dom-module id="home-file">
  <template>
    <style>
      	.content{
				background: #E9EAED;
				justify-content: center;
				margin: 0 auto;
				display: -webkit-box;
				display: -moz-box;
				display: -ms-flexbox;
				display: -webkit-flex;
				display: flex;
				flex-flow: row wrap;
				-webkit-flex-flow: row wrap;
				-moz-flex-flow: row wrap;
				-ms-flex-flow: row wrap;
			}	
			.handle span{
				color: #9C27B0;
				text-transform: uppercase;
				font-size: 11px;
				font-weight: 500;
			}
			iron-image{
				margin: 0 auto;
				width: 120px;
				height: 120px;
				border-radius: 50%;
				border: 0.5px solid #FFF;
				box-shadow: 0 1px 3px rgba(0,0,0,0.12),0 1px 2px rgba(0,0,0,0.24);
				top: 70px;
				display: block;
				position: relative;
				margin-top: -64px;
				background-color: lightgray;
				z-index:1;
			}
			h4{
				font-size: 20px;
				font-weight: 400;
			}
			p{
				font-size: 15px;
				line-height: 1.5;
			}
			paper-icon-button{
				color:#383838;
				height: 34px;
				width: 34px;
			}														
		
      
      
      
      paper-card {
        
                margin: 0 auto;
        				margin-top: 12px;
        				margin-bottom: 24px;
                padding: 16px;
                border-radius: 2px;
                @apply(--layout-vertical);
                @apply(--center-justified);
                max-width: 460px%;
                
                width:90%;
                }
      .paper-center{
        @apply(--layout-vertical);
      @apply(--center-justified);
      max-width: 600px;
      margin-bottom:48px;
      margin-left: auto;
      margin-right: auto;
      text-align:center;
      padding-top: 48px
      }
      
      :root{
            /* custom CSS property */
            --paper-tabs-selection-bar-color: var(--accent-color);
            --paper-tab-ink: var(--accent-color);
            /* custom CSS mixin */
            --paper-tabs: var(--default-primary-color);
            
            }
            
            paper-toolbar + paper-toolbar {
      margin-top: 20px;
    }
    
    
    .spacer {
      @apply(--layout-flex);
    }
    </style>
    <body>
    <div class="card-container">
     <iron-image sizing="cover" preload src="../../images/misc/pic.jpg" ></iron-image>
  <paper-card >
    <div class="card-content">
    </div>
    </paper-card>
    </div>
    </body>
  </template>
  <script>
    Polymer ({
      is:'home-file'
    })
  </script>
</dom-module>`

**Comment by JosefJezek** [comment]
Sorry, I dont time...
