### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by dominik0711** [StartPolymer/polymer-starter-kit-plus#47]
My application based on [Polymer-PSK+][1] and `ES2015`. Using my distributed version of the application I'll receive the following error:
```
Uncaught TypeError: Cannot read property 'trim' of undefined (elements.js line 5832)
```

The reason for this is due to 'missing' properties of Polymer paper-input-container-underline element, see:

![image](https://cloud.githubusercontent.com/assets/1011188/15632626/07f1ea20-2599-11e6-9a26-74c7ca254c39.png)

![image](https://cloud.githubusercontent.com/assets/1011188/15632634/36b590b4-2599-11e6-8eb0-121871de45d7.png)

The assignment to `properties[m[1]]` fails due to `(m[2] || m[3]).trim();`:
```
m[2] = "" 
and m[3] = undefined
```

Any hints how to solve this problem and how to use the distributed version of my application?

  [1]: https://github.com/StartPolymer/polymer-starter-kit-plus

**Comment by JosefJezek** [comment]
What is distributed version?

**Comment by dominik0711** [comment]
Sorry! Distibuted version means vulcanized version of the project

**Comment by JosefJezek** [comment]
Do you have latest version node, bower and npm? Delete cache of packages...

**Comment by JosefJezek** [comment]
https://gist.github.com/bab4fce0ac19f31bbfa8

**Comment by JosefJezek** [comment]
I am creating new template... Check out this repo https://github.com/StartPolymer/progressive-web-app-template
